apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: LoadBalancer
metadata:
  name: truenas-lb
spec:
  backendServerSelector:
    harvesterhci.io/vmName:
      - truenas
  ipPool: localnetworkips
  ipam: pool
  listeners:
    - backendPort: 22
      name: ssh
      port: 22
      protocol: TCP
    - backendPort: 80
      name: http
      port: 80
      protocol: TCP
    - backendPort: 443
      name: https
      port: 443
      protocol: TCP
    - backendPort: 445
      name: samba
      port: 445
      protocol: TCP
    - backendPort: 2049
      name: nfstcp
      port: 2049
      protocol: TCP
    - backendPort: 2049
      name: nfsudp
      port: 2049
      protocol: UDP
    - backendPort: 111
      name: rpcbind
      port: 111
      protocol: TCP
    - backendPort: 111
      name: rpcbindudp
      port: 111
      protocol: UDP
    - backendPort: 9000
      name: minio
      port: 9000
      protocol: TCP
    - backendPort: 9002
      name: minio2
      port: 9002
      protocol: TCP  
  workloadType: vm
  status:
status:
  address: 192.168.1.30
  allocatedAddress:
    gateway: 192.168.1.1
    ip: 192.168.1.30
    ipPool: localnetworkips
    mask: 255.255.255.0