#cloud-config
hostname: ${NAME}
timezone: ${TIME_ZONE}
preserve_hostname: false
package_update: true
package_upgrade: true
users:
  - default
  - name: ubuntu
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${SSH_PUBLIC_KEY}
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: "${NEW_PASSWORD}"
chpasswd:
  expire: false

packages:
  - qemu-guest-agent
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - software-properties-common
  - nfs-common
  - ufw

write_files:
  - path: /etc/containerd/certs.d/docker.io/hosts.toml
    owner: root:root
    permissions: '0644'
    content: |
      server = "https://registry-1.docker.io"

      [host."http://${REGISTRY}"]
        capabilities = ["pull", "resolve"]
        skip_verify = true 
  
runcmd:
  - [ systemctl, enable, qemu-guest-agent]
  - [ systemctl, start, qemu-guest-agent]
  # Disable swap and prevent it from being mounted again
  - [ swapoff, -a ]
  - [ sed, -i, '/ swap / s/^\(.*\)$/#\1/', /etc/fstab ]
  # Update apt and install containerd first
  - [ apt, update ]
  # Install kube packages from the added repository and hold them
  - ufw allow, 22/tcp                    # SSH
  # Kubernetes API server (masters only, but safe for all)
  - ufw allow 6443/tcp
  # etcd (masters only)
  - ufw allow 2379:2380/tcp
  # kubelet API for all nodes
  - ufw allow 10250/tcp
  # kube-scheduler + controller-manager (masters only)
  - ufw allow 10257/tcp
  - ufw allow 10259/tcp
  # NodePort range
  - ufw allow 30000:32767/tcp
  # For Flannel (VXLAN)
  - ufw allow 8472/udp
  # For Calico (if you use it)
  - ufw allow 179/tcp
  # For kubeadm control-plane node load balancing (optional)
  - ufw allow 10256/tcp
  # Enable UFW
  - |
    cat <<EOF >> /etc/hosts
    # Kubernetes cluster nodes
    192.168.1.60 master-01
    192.168.1.61 worker-01
    192.168.1.62 worker-02
    192.168.1.63 worker-03
    EOF
  - |
    # Detect first non-root NVMe disk
    DISK=$(lsblk -dn -o NAME,TYPE | awk '$2=="disk"{print $1}' | grep nvme | head -n 1)

    if [ -z "$DISK" ]; then
      echo "No NVMe disk found"
      exit 1
    fi

    DEVICE="/dev/$DISK"

    echo "Using disk: $DEVICE"

    # Create partition if none exists
    if ! lsblk $${DEVICE} | grep -q part; then
      parted -s $DEVICE mklabel gpt
      parted -s $DEVICE mkpart primary 0% 100%
    fi

    PARTITION="$${DEVICE}p1"

    # Create filesystem if none exists
    if ! blkid $PARTITION; then
      mkfs.xfs -f $PARTITION
    fi

    mkdir -p /mnt/nvme

    UUID=$(blkid -s UUID -o value $PARTITION)
    echo "UUID=$UUID /mnt/nvme xfs defaults,nofail 0 2" >> /etc/fstab

    mount -a  
  #- echo "y" | ufw enable
  # Restart services
  #- systemctl restart ufw
# End of cloud-config
