#cloud-config
hostname: ${NAME}
timezone: ${TIME_ZONE}
preserve_hostname: false
package_update: true
package_upgrade: true
users:
  - default
  - name: ubuntu
    groups:
      - sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: "${NEW_PASSWORD}"
chpasswd:
  expire: false
disk_setup:
  /dev/sdb:
    table_type: gpt
    layout: true
    overwrite: false
fs_setup:
  - label: data
    filesystem: xfs
    device: /dev/sdb1
    overwrite: false
mounts:
  - ["/dev/sdb1", "/var/lib/longhorn", "xfs", "defaults,noatime", "0", "2"]
packages:
  - qemu-guest-agent
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - software-properties-common
  - nfs-common
  - ufw
runcmd:
  - [ systemctl, enable, qemu-guest-agent]
  - [ systemctl, start, qemu-guest-agent]
  # Disable swap and prevent it from being mounted again
  - [ swapoff, -a ]
  - [ sed, -i, '/ swap / s/^\(.*\)$/#\1/', /etc/fstab ]
  # Update apt and install containerd first
  - [ apt, update ]
  # Install kube packages from the added repository and hold them
  - ufw allow, 22/tcp                    # SSH
  # Kubernetes API server (masters only, but safe for all)
  - ufw allow 6443/tcp
  # etcd (masters only)
  - ufw allow 2379:2380/tcp
  # kubelet API for all nodes
  - ufw allow 10250/tcp
  # kube-scheduler + controller-manager (masters only)
  - ufw allow 10257/tcp
  - ufw allow 10259/tcp
  # NodePort range
  - ufw allow 30000:32767/tcp
  # For Flannel (VXLAN)
  - ufw allow 8472/udp
  # For Calico (if you use it)
  - ufw allow 179/tcp
  # For kubeadm control-plane node load balancing (optional)
  - ufw allow 10256/tcp
  # Enable UFW