name: Terraform Init
on: push

jobs:
  terraform:
    runs-on: self-hosted
    container:
      image: hashicorp/terraform:1.9.5
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      NGINX_PROXY_MANAGER_HOST: ${{ secrets.NGINX_PROXY_MANAGER_HOST }}
      NGINX_PROXY_MANAGER_USERNAME: ${{ secrets.NGINX_PROXY_MANAGER_USERNAME }}
      NGINX_PROXY_MANAGER_PASSWORD: ${{ secrets.NGINX_PROXY_MANAGER_PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform -chdir=cloudflare init 
      - name: Terraform Plan        
        run: terraform -chdir=cloudflare plan -input=false