name: Terraform Init
on: push

jobs:
  terraform:
    runs-on: self-hosted
    container:
      image: hashicorp/terraform:1.9.5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform -chdir=cloudflare init 
      - name: Terraform Plan
        run: terraform -chdir=cloudflare plan -input=false