name: Terraform Init
on: push

jobs:
  terraform:
    runs-on: [self-hosted, Precis, Leon]
    container:
      image: hashicorp/terraform:1.9.5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init /cloudflare
      - name: Terraform Plan
        run: terraform plan /cloudflare -input=false
