name: Terraform Init
on: push

jobs:
  terraform:
    runs-on: self-hosted
    container:
      image: hashicorp/terraform:1.9.5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform -chdir=cloudflare init 
      - name: Terraform Plan
        env:
          TF_VAR_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}          
          TF_VAR_NGINX_PROXY_MANAGER_URL: ${{ secrets.NGINX_PROXY_MANAGER_URL }}
          TF_VAR_NGINX_PROXY_MANAGER_USERNAME: ${{ secrets.NGINX_PROXY_MANAGER_USERNAME }}
          TF_VAR_NGINX_PROXY_MANAGER_PASSWORD: ${{ secrets.NGINX_PROXY_MANAGER_PASSWORD }}
        run: terraform -chdir=cloudflare plan -input=false